name: xfyy_demo
description: 讯飞语音WebSocket传输demo
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  # 格式化
  intl: ^0.17.0
  # 加密
  crypto: ^3.0.2
  # webSocket 连接
  web_socket_channel: ^2.2.0
  # 文件路径获取
  path_provider: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:

